# 基于属性的测试
<!-- 2020.04.20 -->
> _Доверяй, но проверяй_
> _(信任，但要核实)_
>
> _-- 俄罗斯谚语_

我们建议为你的函数编写单元测试。你要做的是根据你对所测试的东西的了解，思考可能会有问题的典型事物。

不过，这段话中潜伏着一个小的但潜在的重大问题。如果你写的是原始代码，而你写的是测试，是否有可能在两者中都表达了一个不正确的假设？代码通过了测试，因为根据你的理解，它做了它应该做的事情。

绕过这个问题的一个方法是让不同的人写测试和被测试的代码，但我们不喜欢这样做：正如我们在话题 41 [_代码测试_](./代码测试.md) 中说的那样，对测试的思考最大的好处之一就是它对你写代码的指导方式。当测试的工作从编码中分离出来，你就失去了这一点。

相反，我们更倾向于另一种方式，即由不同意你的先入为主的计算机为你做一些测试。

## 契约、反变量和属性
在话题 23 [_契约设计_](../Chapter4/契约设计.md) 中，我们讲到了这样一个概念，即代码有它所满足的契约：当你给它输入时，你满足了条件，它就会对它所产生的输出做出一定的保证。

还有一些代码的不变性，即当它通过一个函数时，对某些状态保持真实的东西。例如，如果你对一个列表进行排序，结果元素数将与原始的元素数相同--长度是不变的。

一旦我们弄清楚了我们的契约和不变性（我们将把这些契约和不变性集合在一起并称为属性），我们就可以用它们来实现测试的自动化。我们最终要做的就是基于属性的测试。

---
## 提示 71 使用基于属性的测试来验证你的假设
---

作为一个人为的例子，我们可以为我们的排序列表建立一些测试。我们已经建立了一个属性：排序后的列表与原始的大小相同。我们还可以声明，结果中的任何元素都不能大于后面的元素。

现在我们可以用代码来表达。大多数语言都有某种基于属性的测试框架。这个例子是在 Python 中，使用的是 Hypothesis 工具和 pytest，但原理是相当普遍的。

下面是测试的完整源码。

```python
from hypothesis import given
from hypothesis.strategies as some
@given(some.lists(some.integers()))
def
    test_list_size_is_inviriant_accross_sorting(a_list):
        original_length = len(a_list)
        a_list.sort()
        assert len(a_list) == original_length
@given(some.lists(some.text()))
def test_sorted_result_is_orderes(a_list):
    a_list.sort()
    for i in range(len(a_list) - 1):
        assert a_list[i] <= a_list[i + 1]
```

下面是我们运行它时的结果。

```bash
> pytest sort.py
======== test session starts =========
...
plugins: hypothesis-4.14.0
sort.py ..
[100%]
======== 2 passed in 0.95 seconds =======
```

没有太多戏剧性的东西。但是，在幕后，Hypothesis 把我们的两个测试都跑了一百次，每次都通过了不同的列表。列表会有长短不一，内容也会不一样。这就好像我们用 200个 随机的名单，分别做了 200 个单独的测试一样。

## 测试数据生成
和大多数基于属性的测试库一样，Hypothesis 给你提供了一种迷你语言来描述它应该生成的数据。这种语言是围绕着对 hypothesis.strategies 模块中的函数的调用来进行的，我们把它别名为 some，只是因为它读起来比较好听。

如果我们写道

```python
@given(some.integers())
```

我们的测试函数会运行多次。每一次，它将被传递一个不同的整数。在这里，我们写道

```python
@given(some.integers(min_value=5, max_value=10).map(lambda x: x * 2))
```

那么我们就可以得到 10 到 20 之间的偶数。

你也可以组成类型，这样

```pytyhon
@given(some.listes(some.integers(min_value=1), max_size=100))
```

将是最多 100 个元素长的自然数的列表。

这不应该是一个关于任何特定框架的教程，所以我们将跳过一堆很酷的细节，而是看一个实际的例子。

## 寻找坏的假设
我们正在编写一个简单的订单处理和库存控制系统（因为总能多出一个）。它用一个 Warehouse 对象来模拟库存水平。我们可以查询一个仓库，查看是否有东西在库存，从库存中取出东西，并得到当前的库存水平。

下面是代码:

```python
class Warehouse:
    def __init__(self, stock):
        self.stock = stock

    def in_stock(self, item_name):
        return (item_name in self.stock) and (self.stock[item_name] > 0)

    def take_from_stock(self, item_name, quantity):
        if(quantity <= self.stock[item_name]):
            self.stock[item_name] -= quantity
        else:
            raise Exception("Oversold {}".format(item_name))

    def stock_count(self, item_name):
        return self.stock[item_name]
```

我们写了一个基本通过了的单元测试。

```python
def test_warehouse():
    wh = Warehouse({"shoes": 10, "hats": 2, "umbrellas": 0})

    assert wh.in_stock("shoes")
    assert wh.in_stock("hats")
    assert not wh.in_stock("umbrellas")

    wh.take_from_stock("shoes", 2)
    assert wh.in_stock("shoes")

    wh.take_from_stock("hats", 2)
    assert not wh.in_stock("hats")
```

然后我们写了一个函数来处理从仓库订购物品的请求。它返回一个 tuple，其中第一个元素是 "ok" 或 "not available"，后面是物品和请求数量。我们还写了一些测试，结果都通过了。

```python
def order(warehouse, item, quantity):
    if warehouse.in_stock(item):
        warehouse.take_from_stock(item, quantity)
        return ("ok", item, quantity)
    else:
        return ("not available", item, quantity)
def test_order_in_stock():
    wh = Warehouse({"shoes": 10, "hats": 2, "umbrellas": 0})
    status, item, quantity  = order(wh, "hats", 1)
    assert status == "ok"
    assert item == "hats"
    assert quantity == 1
    assert wh.stock_count("hats") == 1

def test_order_not_in_stock():
    wh = Warehouse({"shoes": 10, "hats": 2, "umbrellas": 0})
    status, item, quantity  = order(wh, "umbrellas", 1)
    assert status == "not available"
    assert item == "umbrellas"
    assert quantity == 1
    assert wh.stock_count("umbrellas") == 0

def test_order_unknown_item():
    wh = Warehouse({"shoes": 10, "hats": 2, "umbrellas": 0})
    status, item, quantity  = order(wh, "bagel", 1)
    assert status == "not available"
    assert item == "bagel"
    assert quantity == 1
```

从表面上看，一切看起来都很好。但在我们出货之前，让我们先添加一些属性测试。

我们知道的一点是，库存不能在我们的交易中出现和消失。这意味着，如果我们从仓库里拿了一些物品，那么我们拿的数量加上当前在仓库里的数量应该和原来在仓库里的数量是一样的。在下面的测试中，我们在测试中，我们在 "帽子 "或 "鞋子 "中随机选择物品参数，数量从 1 到 4 中选取，进行测试。

```python
@given(item = some.sampled_from(["shoes", "hats"]), quantity = some.integers(min_value = 1, max_value = 4))
def test_stock_level_plus_quantity_equals_original_stock_level(item, quantity):
    wh = Warehouse({"shoes": 10, "hats": 2, "umbrellas": 0})
    initial_stock_level = wh.stock_count(item)
    (status, item, quantity) = order(wh, item, quantity)
    if status == "ok":
        assert wh.stock_count(item) + quantity == initial_stock_level
```

我们来运行它：

```bash
$ pytest stock.py
...
stock.py:72:
-------------------------
stock.py:76: in test_stock_level_plus_quantity_equals_original_stock_level
(status, item, quantity) = order(wh, item, quantity)
stock.py:40: in order
    warehouse.take_from_stock(item, quantity)
-------------------------
self = <stock.Warehouse object at 0x10cf97cf8>, item_name = 'hats'
    quantity = 3

  def take_from_stock(self, item_name, quantity):
    if quantity <= self.stock[item_name]:
        self.stock[item_name] -= quantity
    else:
> raise Exception("Oversold {}".format(item_name))
    E       Exception: Oversold hats

    stock.py:16: Exception
    ---------------------------- Hypothesis ----------------------------
    Falsifying example:
     test_stock_level_plus_quantity_equals_original_stock_level(item='hats', quantity=3)
```

warehouse.take_from_stock 炸开了：我们试图从仓库里取出三顶帽子，但仓库里只有两顶库存。
我们的属性测试发现了一个错误的假设：我们的 in_stock 函数只检查至少有一个给定商品的库存。相反，我们需要确保我们有足够的库存来填补订单。

```python
def in_stock(self, item_name, quantity):
    return (item_name in self.stock) and (self.stock[item_name] >= quantity)
```

我们也一并更改 order 函数：

```python
def order(warehouse, item, quantity):
    if warehouse.in_stock(item, quantity):
        warehouse.take_from_stock(item, quantity)
        return ("ok", item, quantity)
    else:
        return ("not available", item, quantity)
```

现在我们的属性测试全都通过了。

## 基于属性的测试往往会给你带来惊喜
在上一个例子中，我们用一个基于属性的测试来检查库存水平是否调整得当。这个测试发现了一个bug，但它不是与库存水平调整有关。相反，它发现了我们的 in_stock 函数中的一个 bug。

这就是基于属性的测试的威力和挫折感。它之所以强大，是因为你设置了一些生成输入的规则，设置了一些验证输出的断言，然后让它开动起来。你永远不知道会发生什么。测试可能会通过。一个断言可能会失败。或者代码可能完全失败，因为它无法处理给它的输入。

令人沮丧的是，要找出失败的原因很棘手。

我们的建议是，当一个基于属性的测试失败时，找出它传递给测试函数的参数，然后用这些值来创建一个单独的、常规的单元测试。这个单元测试对你来说有两个作用。首先，它可以让你专注于问题的解决，而不需要基于属性的测试框架对代码进行额外的调用。第二，这个单元测试可以作为回归测试。因为基于属性的测试会生成随机值，这些值会被传递到你的测试中，所以不能保证下次运行测试时，你的测试会使用同样的值。拥有一个强制使用这些值的单元测试，可以确保这个 bug 不会被忽略。

## 基于属性的测试也可以帮助你的设计
当我们谈到单元测试时，我们说过，其中一个主要的好处是它让你思考你的代码的方式：单元测试是你的 API 的第一个客户端。

基于属性的测试也是如此，但方式略有不同。它们让你从不变性和契约的角度来思考你的代码；你知道什么是不能改变的，什么是必须真实的。这种额外的洞察力对你的代码有一种神奇的效果，它可以消除边缘案例，并突出显示那些让数据处于不一致状态的函数。

我们认为，基于属性的测试与单元测试是相辅相成的：它们解决了不同的问题，并且各自带来了各自的好处。如果你目前还没有使用它们，那就试试吧。

## 相关内容包括
- 话题 25 [_断言式编程_](../Chapter4/断言式编程.md)
- 话题 23 [_契约设计_](../Chapter4/契约设计.md)
- 话题 45 [_实用入门套件_](../Chapter9/实用入门套件.md)

## 练习
### 练习 30（尽可能回答）
再看仓库的例子。还有没有其他属性可以测试的？

### 练习 31（尽可能回答）
贵公司装运机械。每台机器都装在一个板条箱里，每个板条箱都是长方形的。板条箱的大小不一。你的工作是编写一些代码，将尽可能多的板条箱包装在一个适合运输车的单层中。你的代码的输出是所有板条箱的列表。对于每个板条箱，该列表给出了在卡车上的位置，以及宽度和高度。可以测试输出的属性是什么？

## 挑战
思考一下你目前正在研究的代码。有哪些属性：契约和不变性？你能不能用一个基于属性的测试框架来自动验证这些？
